### ISSUE TITLE
Anonymize data from Zanzibar

### ISSUE THREAD

**Issue by mikeymckay** [ICTatRTI/coconut-analytics#104]
Script for anonymizing real data from Zanzibar.
1) Scrub phone numbers
2) Scrub names
3) Randomize lat/long
4) Change DMSO password

mobile.cococloud.co will then connect to this, testers/users will be guided to use actual DMSO accounts

**Comment by gmcressman** [comment]
@mikeymckay , not certain that all data have been anonymized. Also, we still need a function that hashes PII/PHI in analytics detail displays. Only authorized personnel should have access to PII/PHI.
