### ISSUE TITLE
Maps: Case pop-up not displayed consistently

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#129]
When case (household) points are displayed on the map, sometimes clicking on a case point will display a pop-up. Sometimes it will not. Sometimes the case number in the pop-up is linked to the case detail. Sometimes it is not. This may be affected by selecting different displays (e.g. heat map on, then heat map off) and perhaps different layers. See whether you can reproduce this.

**Comment by workmaps** [comment]
@gmcressman: I moved 129 back over to ready. While there is consistency now between the information in the popups for Cases and for Cases (time) the popups don't always popup after turning off the admin layers.

**Comment by gmcressman** [comment]
Yeah! It's fabulous to have this fixed. Done.
