### ISSUE TITLE
Case data repeats in case detail modal dialog

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#135]
I'm scrolling down through the detail in case #111067. After the last household member record, I see the USSD Notification record again, and then the case record detail is repeated.

![image](https://cloud.githubusercontent.com/assets/329768/16381256/a135dc8e-3c49-11e6-8cc3-93a662456105.png)

**Comment by scloo** [comment]
Can you outline the steps  how you got to Case 111067?

**Comment by gmcressman** [comment]
Steps:

1.       Display map

2.       Click on point on map

3.       Click on case number in pop-up (the case number was 111067

4.       Scroll down case detail in model dialog

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>
