### ISSUE TITLE
User Account: Not able to type into Username field after error

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#139]
1. Add new user (account(
2. Leave Username field blank.
3. Save
4. See Error: "Required field(s): Username"
5. Try to type into Username field.

![image](https://cloud.githubusercontent.com/assets/329768/16390284/fa92d860-3c6f-11e6-8610-b79ac295d1d5.png)

**Comment by scloo** [comment]
Cause was Username field cannot be updated for editing a current user. But it was also applied to adding New user. Bug fixed.
