### ISSUE TITLE
Graph: Time to Notify

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#143]
![image](https://cloud.githubusercontent.com/assets/329768/16429829/cd62c59e-3d46-11e6-9bf9-b09bc79d696c.png)

The top graph is "Number of Malaria Cases". The second graph is "Proportion of Malaria Cases". They reveal different things. Both graphs are useful. 

- [x] This is the time between the "Diagnosis Date" and the "USSD Case Notification" or the "Case Notification" date. Which is it?

![image](https://cloud.githubusercontent.com/assets/329768/16430660/b3784eb6-3d4a-11e6-9483-29fbd4dff556.png)

Coconut Surveillance is one of very few systems that can provide this information. It’s possible that it’s unique to CS. The “Number” and “Proportion” graphs reveal different things, so both are useful.

The data are aggregated by month. Would it be useful to let the user select any other data aggregation period (e.g. week)?

The **thresholds** for this graph (within 24 hours, 25-72 hours, over 72 hours, not followed up) will not be the same for all countries. They need to be soft, and we need a way for them to be changed easily in the system by a non-programmer. 

- [x] Data query done
- [ ] "Number of Malaria Cases" graph done.
- [ ] "Proportion of Malaria Cases" graph done.
- [x] Date selector (Start Date, End Date) works.
- [x] User can select By Month or By Week.
- [ ] Admin able to change response time **thresholds**. This needs to be configurable in the Admin section of the Analytics app.

**Comment by mikeymckay** [comment]
Time to Notify should refer to the amount of time it takes for a health facility to notify Coconut Surveillance of a new case. We can only determine this after the visit to the health facility where get the diagnosis date at the facility. This date can then be compared to the createdAt on the USSD Notification. A couple of issues though:

* We don't have hourly resolution on the diagnosis date of the facility, so this should probably be reported as days 1, 2-3, 3+ to emphasis that we don't have hours
* This is an example where we should *not* use the Index Case Diagnosis Date, as the Index Case Diagnosis Date uses alternative values when the Facility record isn't present. If there is no facility record, then it should not be used in the graph. Two ways to get the facility record: Add it to the summary case index or do an old fashion Reports.getCases() lookup.
