### ISSUE TITLE
Graph: Number of Persons Tested and Number Positive

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#145]
![image](https://cloud.githubusercontent.com/assets/329768/16431056/bba2c060-3d4c-11e6-89f6-a8601d5550e8.png)

This graph is an odd combination of bars and lines. It is the same as the "Number of Malaria Cases" graph, but adds series for:

- Number of household members tested
- Number of household members tested positive

I suggest that we try all three lines on the same graph:

1. Number of Case Notifications from Health Facilities
2. Number of Persons Tested
3. Number of Persons Tested Positive

(In other countries they may be testing for different species of _Plasmodium_, but we don't have that in Zanzibar.)

The following is the same graph, but without the "Persons Tested", and shown as a bar graph. The second graph actually shows the percentage of cases with travel. That is a very different graph.

![image](https://cloud.githubusercontent.com/assets/329768/16431285/e72a5210-3d4d-11e6-9ba4-7d6e5c052213.png)

The unit of time aggregation is month. We could easily enable the user to select Day, Week, or Month.

- [x] Data query done.
- [ ] Graph done.
- [ ] Date selector works.
- [ ] User can select By Week or By Month

**Comment by scloo** [comment]
@mikeymckay,  I need some help here to determine which attributes to use.
1. Number of Case Notifications from Health Facilities
2. Number of Persons Tested
3. Number of Persons Tested Positive

To get the above, I'm trying to group the records by each of the requirements above.
So for each record, how can I determine if the index case has been test and whether he/she is tested positive.  Would having a date for "Index Case Diagnosis Date" implies the person was tested? And "Number Positive Cases Including Index" greater than 0 means Index case is positive?

#1 I'm not so sure what that means.

Correct me if I am wrong,  each record returned by caseCountIncludingSecondary is an individual case, right?

**Comment by mikeymckay** [comment]
For this one just use the caseCounter view (grouped) again with the following properties:

      "Has Notification"
      "Number Household Members Tested Positive"
      "Number Household Members Tested"

**Comment by gmcressman** [comment]
Done. The legend abbreviations are a bit odd, but I can't think of a better one. Closed.
