### ISSUE TITLE
Graph: Attendance

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#146]
![image](https://cloud.githubusercontent.com/assets/329768/16431649/9019d232-3d4f-11e6-9399-b9973b6bf279.png)

This graph shows the number of index cases (reported by a health facility Out Patient Department [OPD])  by age (<5 Years of Age, 5+ Years of Age). The time scale is by week. That should be fine for us, but note that we could cross year boundaries. We need to handle that in the X-axis labeling. 

I don't know why this is done as a bar graph. This isn't sensitive enough to show changes over time. I suggest we try this as a line graph, with two lines.

- [x] Data query done.
- [ ] Graph done.
- [ ] Date selector works.

**Comment by mikeymckay** [comment]
There are at least 2 ways to do this already...but I think a new query will be better.

**Comment by mikeymckay** [comment]
Note that this graph does not show malaria cases, but rather the total number of people going to health facilities for any problem.

**Comment by gmcressman** [comment]
We don’t have those numbers in Coconut Surveillance. We should strike this graph, correct?

What other graphs should be on the priority list?

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by mikeymckay** [comment]
We do. Query is done, just testing it.

**Comment by mikeymckay** [comment]
view is weeklyDataCounter, group=true. I have included the zone (PEMBA/UNGUJA) at the beginning in case you are up to splitting this into two graphs.

**Comment by mikeymckay** [comment]
I should also mention that for this query you should not pass in a startkey to select the dates. You need to download the full dataset and then extract the appropriate dates. The full dataset is only 117KB so no need to optimize that one.

**Comment by mikeymckay** [comment]
As I expanded this query to also return the testing rate for #147 the result got bigger. So I moved the year and week to the front of the key. Now it's about 10KB for a year's worth of data. You can use startkey and endkey to limit the data that is being returned to the required date range:
```

start_key: [startyear, startweek]
end_key: [endyear,endweek, {}]
```

or even:

```
start_key: [startyear]
end_key: [endyear,{}]
```

**Comment by gmcressman** [comment]
Done. Closed.
