### ISSUE TITLE
Graph: Test Rate

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#147]
![image](https://cloud.githubusercontent.com/assets/329768/16431974/03fbf594-3d51-11e6-8fd7-9311bc083cf6.png)

This graph shows the percentage of OPD (health facility) cases that tested positive by age group (<5 Years of Age, 5+ Years of Age). This is shown as a line graph, which I believe is the best form for this over time. The time scale is by week, which should be fine. The time scale my span years, so we need to figure out how to handle years in labeling the X axis.

OPD = Out Patient Department. These are patients who were tested and diagnosed at health care facilities. These do not include patients tested at households.

- [x] Data query done.
- [ ] Graph done.
- [ ] Date selector works.

**Comment by scloo** [comment]
What would be the base number to calculate the percentage? Is it the total of all the cases tested positive over the date range?

**Comment by gmcressman** [comment]
Number of positive cases / number of cases tested

**Comment by mikeymckay** [comment]
This isn't the number of cases that tested positive. This is the number of OPD cases that were tested for malaria, regardless of whether they were found positive for malaria or not. I have added the required data to the weeklyDataCounter view. Here are the calcs for each line in the graph:

Line 1:
Numerator is total number tested: "MAL POS < 5" + "MAL NEG < 5"
Denominator is total number of OPD cases <5

Line 2:
Numerator is total number tested: "MAL POS >= 5" + "MAL NEG >= 5"
Denominator is total number of OPD cases >=5

**Comment by mikeymckay** [comment]
The reason that this is important is because it is useful to know if the health facilities are testing enough for malaria. If the numbers dip it could suggest that there is a test kit shortage.

**Comment by gmcressman** [comment]
Done. Closed.
