### ISSUE TITLE
Dashboard: Determine key indicators to display at top

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#149]
![image](https://cloud.githubusercontent.com/assets/329768/16463306/40605874-3e03-11e6-9515-faf2df50531e.png)

@mikeymckay should advise which indicators we should display at the top of the Dashboard. He will also probably need to write the necessary queries.
@cjenkins-rti should review and revise the design. She may also implement design changes.
@scloo is familiar with this code.

Suggested candidate indicators:

1. Number of epidemic threshold Alerts in selected time period. Link to Epidemic Thresholds report.
2. Number of epidemic threshold Alarms in selected time period. Link to Epidemic Thresholds report. Perhaps #1 and #2 should be combined into a single number.
3. Number of errors detected by system. Link to Errors Detected by System report. (Why don't we shorten this report name to System Errors?)
4. Number of cases. Link to ??
5. Cases without completed facility record 24 hours after facility notification. Link to Users Report - How Fast Are Followups Occuring (Occurring has two "r"s. Correct spelling). (Can we shorten the name of this report too? It's much easier to read and understand shorter text on the screen.  How about "Followup by User"?
6. Cases without complete household record 48 hours after facility notification. Same report link as #5?
7. Median time from SMS sent to Case Notification on tablet	 Same report link as #5?.
8. Median time from Case Notification to Complete Facility. Same report link as #5?
9 Median time from Complete Facility to Complete Household. Same report link as #5?
10. Other? Trend in number of cases compared to previous time period?

**Comment by gmcressman** [comment]
We need input on  which indicators should be displayed. I will ask Jeremiah.

**Comment by gmcressman** [comment]
Question sent to Jeremiah.

**Comment by gmcressman** [comment]
Jeremiah has not responded. And we need to move this forward now. We can always make changes later based on user feedback.

Limit the number of indicators at the top of the dashboard to 6.
Each indicator tile will be linked to one existing report.


The indicators will be as follows:

1. Number of epidemic threshold Alerts in selected time period. Link to Epidemic Thresholds report.

2. Number of epidemic threshold Alarms in selected time period. Link to Epidemic Thresholds report. Perhaps #1 and #2 should be combined into a single number.

3. Number of cases. Link to Analysis report.

4. Cases without completed facility record 24 hours after facility notification. Link to Users Report - How Fast Are Followups Occurring. 

5. Cases without complete household record 48 hours after facility notification. Same report link as #5?

6. Number of errors detected by system. Link to Errors Detected by System report. (Why don't we shorten this report name to System Errors? I'll add a separate issue about shortening report titles.)

**Comment by mikeymckay** [comment]
Here is the wishlist. 8 indicators. I think we will probably set the default date range to be from the beginning of the year to the present - but I am not totally certain about this.

 # ALERTS
 # ALARMS
 # NOTIFIED CASES
 # CASES NOT FOLLOWED UP
 # HSAT (ADDITIONAL POSITIVE CASES FROM HOUSEHOLD)
 TEST RATE FROM HOUSEHOLDS (# people tested / # people in household - 1)
 # FSAT (ADDITIONAL POSITIVE CASES FROM FOCAL TESTING - (ACD))
 PERCENT CASES SUSPECTED TO BE IMPORTED

**Comment by gmcressman** [comment]
HSAT = Household Screening and Testing (members of the index case household)
FSAT = Facility Screening and Testing (at a clinic, hospital or other health care facility)
MSAT = Mass Screening and Testing (members of surrounding households within a designated area, such as within 150 meters of an index case household)

**Comment by gmcressman** [comment]
We'll need to shorted the text on the tiles.

# ALERTS
# ALARMS
# NOTIFIED
# NOT FOLLOWED UP
# HSAT
% HSAT TESTED
# FSA
% IMPORTED

We could use hover-over or some kind of help to provide more information about what these mean. We also need to link each of these to a report for more details.

**Comment by mikeymckay** [comment]
From what I understand, focal screening could also apply when you setup a desk in a village and you invite people to come for testing. Mass screening really focuses on screening _everyone_ - but I could be wrong about that. HSAT simply means that we want the number of positive cases (we also had a useful discussion about 'positive' vs 'suspected' - Jeremiah believes strongly in using positive) found at the household. Within Coconut Surveillance, on the Household Question Set the first question asks the reason for visiting the household: Index Case Household, Neighbor Household, Mass Screen. I added Mass Screen in an attempt to capture ACD (Active Case Detection) scenarios - but ideally it would probably be better to distinguish between Focal and Mass. So far Coconut Surveillance hasn't been used for any ACD/Focal/Mass screening, but if they can get enough tablets, it probably will be used in the coming months.

**Comment by mikeymckay** [comment]
@scloo - leave it to me to build the queries for you. Description for what is needed is below.

# ALERTS - need a new view
# ALARMS - need a new view
# NOTIFIED - new combo view with reduce
# NOT FOLLOWED UP - new comboe view with reduce
# HSAT - new combo view with reduce
% HSAT TESTED - new combo view with reduce (need to add in household members to get baseline)
# FSA  - new combo view with reduce (need to add new field that reports "mass screen" for reason for visiting household)
% IMPORTED - new combo with with reduce (need to add new field to extract "imported)

**Comment by gmcressman** [comment]
Done.

**Comment by mikeymckay** [comment]
Pasting in from slack:

HSAT is in caseCounter:  "Number Household Members Tested Positive"
Let's ignore FSAT, since it's been 0 thus far
@stephen ^^^^^ that should give you alert and alarm counts. Turn reduce on. (alertAlarmCounter)
