### ISSUE TITLE
Add/Edit User: Role should be selection list

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#152]
Is making this field a selection list pending some other changes?

**Comment by scloo** [comment]
Material Design Lite does not have a Select input component. Have to rely on third party add-on. But the last add-on I tried works fine for single select but does not cater for multiple select. I have found another version of Material Design library that have this. But it is a replacement for MDL and if used together with MDL will break many things. So still pending on finding an appropriate solution.

**Comment by scloo** [comment]
Changed the this field input to checkboxes. Add the roles options in the System Settings under Database.
