### ISSUE TITLE
Enable logo upload

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#154]
Enable app logo upload in systems settings.

**Comment by scloo** [comment]
Implemented selection of filename from directory. Still need to add uploading of file to couchdb.

**Comment by scloo** [comment]
Logo upload implemented. In System Settings, clicking the logo name will also pop up the logo image for preview.

**Comment by gmcressman** [comment]
Very cool. We may need to provide some guidance on size and format of the file, but we can do that in the docs.
