### ISSUE TITLE
Maps: Differences in points displayed when time slider on.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#156]
Same date selector values.

Time slider off:
![image](https://cloud.githubusercontent.com/assets/329768/16600624/03fb16f8-42d6-11e6-8586-1940acb1c7cb.png)

Time slider on:
![image](https://cloud.githubusercontent.com/assets/329768/16600649/36317892-42d6-11e6-8e68-c24af268daa9.png)

Note the one-day difference between the date selector values the first and last days on the time slider. the differences in the points displayed appear to due to the differences between the start and end dates of the date selector, and the start and end dates on the time slider. This is particularly evident when the date selector is in week mode. When in date mode, the time slider is always a day off on its start day and end day.

**Comment by gmcressman** [comment]
Nope. It helps. It doesn't fix the issue. If you can't see it, we'll need to look at it together.

**Comment by gmcressman** [comment]
@workmaps : Look at the two map images in this issue. They can be reproduced by 1) displaying the map with, say, 2016 Week 20 - 21; 2) look at the points on the map; 3) click on the time slider option to activate the time slider; 3) look at the points on the map again; 4) click on the time slider option again to de-activate the time slider; 5) look at the points on the map again. From this it should be clear that the points displayed are different, depending on whether the time slider is activated. And yet, the time slider window appears to be initialized with the same start and end dates as the time slider bar, which now has start and end dates that match the date selector. Somehow the dates in the data query don't reflect this. What am I seeing here?

**Comment by workmaps** [comment]
@gmcressman I am seeing that too, now. I will revisit this this afternoon.

**Comment by workmaps** [comment]
@gmcressman: I looked into this issue further and found that the dates of the points that disappear when the time slider button is clicked are outside of the date range designated by the date selector.  I think that I am using the wrong attribute for date. 

@mikeymckay: should I be using 
date: malariaCase.Household?.lastModifiedAt  
to determine date in the reportResult function or is there a better way?

Here is a little more of the reportResults function:

  reportResults = (results) ->
        casesGeoJSON.features =  _(results).chain().map (malariaCase) ->
          if malariaCase.Household?["HouseholdLocation-latitude"]
            { 
              type: 'Feature'
              properties:
                MalariaCaseID: malariaCase.caseID
                hasAdditionalPositiveCasesAtIndexHousehold: malariaCase.hasAdditionalPositiveCasesAtIndexHousehold()
                numberOfCasesInHousehold: malariaCase.positiveCasesAtIndexHousehold().length
                NumberofLLIN: malariaCase.Household.NumberofLLIN
                SleepingSpaces: malariaCase.Household.NumberofSleepingPlacesbedsmattresses
                RecentTravel: malariaCase.Facility.TravelledOvernightinpastmonth
                date: malariaCase.Household?.lastModifiedAt 



Thanks, Tyler

**Comment by mikeymckay** [comment]
malariaCase.indexCaseDiagnosisDate()
or
malariaCase.householdMembersDiagnosisDates()

**Comment by workmaps** [comment]
@mikeymckay, I've tried: 

date: malariaCase.householdMembersDiagnosisDates()

and also: 

date: malariaCase.indexCaseDiagnosisDate()

The output for these two queries seem the same. However, The date range is still outside of the date range that I set using:  

    Reports.getCases
      startDate: startDate
      endDate: endDate
      success: reportResults

Not sure if I'm doing something else wrong or not. Do you see anything that stands out?

**Comment by gmcressman** [comment]
This is fixed. Done.
