### ISSUE TITLE
Error when UPDATEing Admin | Settings

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#160]
I've seen this several times. In this case, I changed the Facilities Editable setting, then clicked on the UPDATE button. I did this again and received the same message. The third time I received the confirmation that the settings had been updated. I'm on a very slow connection, but I can't see how that could be related to this error.

![image](https://cloud.githubusercontent.com/assets/329768/16640713/5bd28b66-43c8-11e6-89d9-f11ea4294674.png)

**Comment by scloo** [comment]
Duplicate with #158. Closing.
