### ISSUE TITLE
Maps: Correct text in map legend

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#167]
Currently:

![image](https://cloud.githubusercontent.com/assets/329768/16741976/c65c8370-4773-11e6-8856-b95855ef3cfb.png)

Should be:

LLIN < Sleeping places
LLIN >= Sleeping places

At least I hope that's the way the query is written.

**Comment by workmaps** [comment]
@gmcressman, I double checked the query. this was only a labeling error. 

query is:

if feature.feature.properties.NumberofLLIN < feature.feature.properties.SleepingSpaces
