### ISSUE TITLE
Bug in threshold report or problem in data?

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#171]
My selections are below:

![image](https://cloud.githubusercontent.com/assets/329768/16744435/24978538-477f-11e6-9508-fe83b039ec8a.png)

When I selected MJINI District to view the cases, I got an empty display. There were errors:

![image](https://cloud.githubusercontent.com/assets/329768/16744462/405b0376-477f-11e6-8922-12efd87fa3ca.png)

**Comment by gmcressman** [comment]
Oops. This may be the same as Issue #161.

**Comment by scloo** [comment]
Bug fixed
