### ISSUE TITLE
Reports: Detail records not displayed

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#172]
![image](https://cloud.githubusercontent.com/assets/329768/16744792/b7e21d66-4780-11e6-9332-f0a4ffc175df.png)

We've seen this before. Is it back?

**Comment by scloo** [comment]
The same issue was in Weekly Facility report. And when I fixed that one, it broke in this report. The same codes are supposed to be used between reports are somewhat inconsistent in handling the object passed to the function.
