### ISSUE TITLE
Reports: Change "tablet" to "mobile device"

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#173]
![image](https://cloud.githubusercontent.com/assets/329768/16744896/48ce5ae2-4781-11e6-927f-4adccdff2863.png)

Steve and Mike, I'm sorry! I missed this before. Since the mobile app could be used on a smart phone, we should change all instances of "tablet" to "mobile device". I found one instance here, but there may be others. Steve, could you please search the Analytics code base for this? Mike, are there instances in the Mobile code base that need to be changed?

**Comment by scloo** [comment]
Looks like there is only one other instance in the same report. Fixed both.
