### ISSUE TITLE
Report: Analysis - Explain why some numbers are highlighted

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#184]
Find a way to explain why some numbers in this report are red.

![image](https://cloud.githubusercontent.com/assets/329768/16960341/16b804f4-4db7-11e6-916e-bf182eca0375.png)

**Comment by scloo** [comment]
From the codes,  the  values in red signifies the maximum value in the column. I guess it is to highlight which cell has the highest value in each column.

**Comment by gmcressman** [comment]
When I look at this, the value in red in a column is not always  the largest number in the column. The code most tell us, and then we need to explain this to the user!

**Comment by scloo** [comment]
Actually it's more accurate to say that it is the largest value in the column for the individual districts, excluding the ALL.

**Comment by gmcressman** [comment]
@scloo is correct. Closing issue.
