### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#186]
Change to generic Coconut favicon.
![image](https://cloud.githubusercontent.com/assets/329768/16960822/fb809bf4-4db8-11e6-8ceb-28173346687f.png)

**Comment by scloo** [comment]
I thought that is the generic Coconut favicon. If not do you have a sample of the favicon?

**Comment by gmcressman** [comment]
I uploaded the icon package to Slack.
