### ISSUE TITLE
Graphs to filter by the specified date range

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#188]

**Comment by scloo** [comment]
One design issue came out of this enhancement. On the Dashboard, the default date is current week, if no dates have been set prior. This will pose an issue because there may not be any data for the week and hence there will be no graphs presented. Generally this will not be a problem on a live server as there will be more records daily. But on a demo or less active site, this will become a problem.

**Comment by gmcressman** [comment]
I agree. One solution is to set the end date to the date of the most recent positive case record, and the start date to 7 days before that. On a demo site, where users can and will be submitted test data, we'll need to restore/reset the database periodically, perhaps every 24 hours.

**Comment by scloo** [comment]
@mikeymckay : How do I pull out the date of the most recent positive case from the DB?

**Comment by scloo** [comment]
I created a view called positiveCasesByDate which also convert the specific dates from string to Date, and then sort that in the DashboardView in order to find the most recent date. Probably not the most efficient way to go about it but serves the purpose until a better solution is conceived.
One question came up though. When someone specify a date range that has no records, it automatically change the date behind the scene to most recent date and start date 7 days earlier. And this date range will be swapped into the date selector box. Problem is unless the user is observant he will not noticed the date change in the date selector, which is now different from what the user specified to begin with.

**Comment by gmcressman** [comment]
Great work on this @scloo. Good point about users probably not noticing the change in the date selector. Could we display a modal dialogue, telling the user that:

"No records were found for the requested date range. The date range has been adjusted automatically to show the most recent records."

This functionality will need to be used for the individual graphs also, correct?

**Comment by scloo** [comment]
This functionality only applies to the Dashboard because of the statistics and graphs to be displayed. This is to avoid the dashboard showing no statistics or empty graphs.
For the others like the individual graphs and maps, they basically display whatever result in the graph or map itself. So if there is no result, nothing will be shown. For example on individual graph, inside the graph box will show "No records found for date range". And for the Map, it just show the maps but no points shown.

We could use popup modal. But I don't quite like having too many popups. An alternative would be display a line of message next to the data selector which will fade out after a predefined number of seconds.

**Comment by gmcressman** [comment]
Agreed. I like your suggestion of a message that would fade out.
