### ISSUE TITLE
Maps: Filter out points (households) above a set GPS accuracy threshold

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#189]
- [ ] Add a GPS accuracy threshold (meters) setting to the global app settings. 

- [ ] On all map displays, filter out points (households) with GPS accuracy above the set GPS accuracy threshold.

**Comment by workmaps** [comment]
@gmcressman accuracy filtered for points <= 50 meters. It reduced points by 1/5 but didn't prevent points from landing in the Indian Ocean. Let me know if you want me to reduce the threshold.

**Comment by gmcressman** [comment]
@workmaps : There is a separate issue for @mikeymckay to rerun the de-identification script without adjusting household coordinates. The theory is that successive runs of this script, which adjusts the coordinates, is the cause of all those households in the water.

**Comment by workmaps** [comment]
@gmcressman: That sounds good. I have it set at 50 as a default and will work with Stephen to make it a setting.  Let me know if we need to reopen this and lower the default setting.

**Comment by gmcressman** [comment]
@workmaps , please coordinate with @scloo to get this into the Admin Settings.
