### ISSUE TITLE
Complete dashboard function

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#19]
- [x] Selected statistics update automatically and are displayed at top of dashboard.

- [ ] User can drill down from selected statistic to detail (e.g. report).

- [x] Highest priority graphs are updated automatically and displayed on dashboard

- [x] User can select a graph to display the selected graph on its own page.

- [x] Date selector at top of dashboard filters data for all dashboard components.

**Comment by scloo** [comment]
Task2 above involves creating new reports. If this is still necessary, I think should create a separate ticket for it.

**Comment by gmcressman** [comment]
@scloo - We received a new set of indicators from Mike, which you've added to the dashboard. Some can be mapped to existing reports.For example, alarms and alerts can be linked to the thresholds report.  Let's see how this works out:

Alerts => Epidemic Thresholds
Alarms  => Epidemic Thresholds
Notified Cases => Analysis
Not Followed up => Users Report - How fast are follow-ups occuring?
HSAT => Analysis
HSAT Tested => Analysis
FSAT =>  Analysis
Imported => Analysis

And numbers in the Dashboard need to match numbers in the report.

@mikeymckay - Please review the above.

**Comment by gmcressman** [comment]
Done. Thanks!
