### ISSUE TITLE
UI: Hash PII before display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#199]
The old reporting app hashes personally identifiable information before displaying record detail. This is because users of Analytics are not case workers, and therefore may not be authorized to access this information.

![image](https://cloud.githubusercontent.com/assets/329768/17141119/f1c6d492-5318-11e6-9605-e6f1ac51e94a.png)

**Comment by scloo** [comment]
Looks like in the old version, it only hashes when the user is not an admin. Is this how we want it to be in the new version?

**Comment by gmcressman** [comment]
We'll need to ask @mikeymckay about this. The question is whether any role other than an authorized user of the mobile app should have access to PII. It makes sense to me to permit an Admin to have access to PII, but we should consult Mike.

**Comment by scloo** [comment]
Unless Mike indicated otherwise later, I have implemented the hashing of PII for non-admin user (Users who do not have admin role set)

**Comment by scloo** [comment]
Just wondering. Since this is only applicable for display, instead of generating a hash, would it be sufficient to just replace names with "***************". The point is merely to hide the names.

**Comment by gmcressman** [comment]
Yes, that would work. Let's make sure there is no PII in data downloads either. I'm pretty sure there is none, but I have not checked that in at least a week.

**Comment by gmcressman** [comment]
Add Contact Mobile # (ContactMobilepatientrelative):
![image](https://cloud.githubusercontent.com/assets/329768/17150430/75c0f09c-533d-11e6-9b36-d4a3b539fe7d.png)
