### ISSUE TITLE
UI: Implement half-icons on case follow-up report

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#208]
Implement half-icons on case follow-up report to indicate incomplete records.

**Comment by scloo** [comment]
Do you remember what the half icon for each category mean? Example in the old version there is the half household, half household member, half facility, half case notification. I do not see an explanation in the over version for these half icons.

**Comment by gmcressman** [comment]
Half and icon indicates and record that is NOT Complete.

**Comment by scloo** [comment]
Done

**Comment by gmcressman** [comment]
There are problems. A half icon should **only** be used to indicate and incomplete question set. 

Notification has not been sent. => should not be a half icon.
Case not followed up to facility after 24 hours. => should not be a half icon.

![image](https://cloud.githubusercontent.com/assets/329768/18569072/6e72ce4c-7b6e-11e6-9d83-95ba80c6e02b.png)

We need to make sure to use symbols and colors consistently to mean the same thing. 

I'm not happy with using three different icons in the Household column. I wish that we had one version of the house icon with a little start beside it to indicate no travel history. This would be consistent. Can this be done?

**Comment by scloo** [comment]
If a half icon should only be used to indicate an incomplete question set, then "case notification is incomplete " should not be a half icon either even though it is tagged as incomplete. My understanding of this incomplete status refers to the Case notification and not the question set. I could be wrong.

"Case not followed up to facility after 24 hours", in my understanding, is considered an incomplete case followup, just as in the case of Case Notification.

This is basically what the program  code indicates. The "Case not followed up to facility after 24 hours" is based on the "notCompleteFacilityAfter24Hours" value. If this value is true, then it is marked with an incomplete. Hence the half icon. Whether this also means the question set is incomplete or not, I can't tell.

Perhaps @mikeymckay can clarify on this.

**Comment by gmcressman** [comment]
Thanks @scloo . @mikeymckay - can you answer this question?
