### ISSUE TITLE
Select JavaScript graphing / charting library

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#21]
Candidates include:

https://d3js.org/
http://n3-charts.github.io/line-chart/#/home (Build on D3 for Angular)
https://developers.google.com/chart/ (includes some MD charts now)
http://www.chartjs.org/

Here is a longer list:

http://www.sitepoint.com/15-best-javascript-charting-libraries/

**Comment by scloo** [comment]
In the older Coconut version, we use Rickshaw , a library built on top of D3. Looks like a good library with good graphs, and not too complicated to implement http://code.shutterstock.com/rickshaw/
