### ISSUE TITLE
Help page content

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#218]
Provide help page content for Help on the More menu.

**Comment by scloo** [comment]
Help Modal is done. Need the content for the details

**Comment by gmcressman** [comment]
Need help with Coconut Surveillance?

The best place to start may be the Coconut Surveillance documentation website.  There you will find information about deploying the system, using the mobile and analytics applications, and the software technology behind the System.  Documentation can also be downloaded from this website in PDF format for use offline.

Still need help? Visit the Coconut Surveillance Community to search for answers or to post a question to the community.

Need expert technical assistance, help considering a new deployment, or have a great idea for collaboration? Contact us to discuss your needs and your ideas.

**Comment by gmcressman** [comment]
Done.
