### ISSUE TITLE
Correct all report titles

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#22]
- [ ] Remove "Reports:" prefix from all reports. It doesn't add any useful information.

- [ ] Make sure the report title uses the same text that appears in the report menu. Reuse this text. It will need to be translated at some point when we support alternate languages.

- [ ] Remove any other report title or subtitle text that does not add information or conflicts with the report title.

![image](https://cloud.githubusercontent.com/assets/329768/14691091/4c3bde7e-071d-11e6-9d37-c1b6ee0e97fd.png)

**Comment by scloo** [comment]
'Reports: prefix' in the title signifies the top level menu title. Example like Activities, Graphs, Admin, etc. So if we remove 'Reports:' prefix from the title, we will have to remove all the others too, to be consistent.

**Comment by gmcressman** [comment]
Good point Steve. At smaller screen sizes the hamburger menu drawer closes. There are currently two levels to the menu. I don't anticipate adding levels. The <level 1 menu selection>: prefix may help orient the user when the hamburger menu drawer is closed. We are not using breadcrumbs, but this serves the same purpose with respect to orientation.

Just make sure the text in the titlebar:

- [ ] Follow the format `<level 1 menu selection>:<level 2 menu selection>`

- [ ] Use the same style (font, color, size)  for all text in the titlebar

Then this issue can be moved to Done.
