### ISSUE TITLE
Maps: Duplicate legends

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#228]
The problem is that I have not been able to reproduce this.

![image](https://cloud.githubusercontent.com/assets/329768/17858053/2acd18c0-6852-11e6-8a77-86ea72a0cb41.png)

**Comment by gmcressman** [comment]
And again. Wish I could figure out how to reproduce this!
![image](https://cloud.githubusercontent.com/assets/329768/17906191/4e2af146-6944-11e6-9485-fb882ecaa92d.png)

**Comment by workmaps** [comment]
I believe that this is solved.

**Comment by gmcressman** [comment]
I have not seen this come back. I think it's solved. Closed.
