### ISSUE TITLE
Add calendar date picker widget

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#23]
- [x] Add a calendar date picker widget, consistent with MD, to all date selection controls.

- [ ] Can we make the date selection control (the little calendar button) more obvious? It's not obvious to me that it is a control that I can use to change the date.

![image](https://cloud.githubusercontent.com/assets/329768/14691186/d9184396-071d-11e6-95f8-757be03a5ddd.png)

**Comment by scloo** [comment]
There are some date picker available with MD design but they depend on other JS framework like Angular, bootstrap-MD. Not been able to find one yet for Backbone. So I'm implementing a simple date-picker widget for now.

**Comment by scloo** [comment]
One option to make it obvious is to put a remark in small font just below the Calendar line saying "Click calendar icon to change dates"

<img width="482" alt="screen shot 2016-04-30 at 11 27 04 pm" src="https://cloud.githubusercontent.com/assets/8493786/14939927/9331d4c6-0f2b-11e6-81be-24ad557fe418.png">

**Comment by gmcressman** [comment]
The need to add instructional text suggests that we could improve this UI element. Let's note this and come back to it later, perhaps when Carol reviews this.
