### ISSUE TITLE
Graph: Change labeling

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#234]
All cases are current diagnosed using RDTs. Therefore they are "suspected". When we have an attribute that distinguishes between clinical, suspected, and confirmed, we'll need to show three lines.

![image](https://cloud.githubusercontent.com/assets/329768/18128266/ef980bb8-6f52-11e6-9dee-7020ba998874.png)

**Comment by scloo** [comment]
Revisiting this ticket, I think we have ended up changing this graph to Number of Positive Cases for Current and Last Year.

So perhaps we can close this ticket?

**Comment by gmcressman** [comment]
Correct. Closing issue now.
