### ISSUE TITLE
Graphs: X-axis label

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#247]
Oops. Changing the time period changes the graduations on the X-axis. Depending on the time period selected by the user, the X-axis may be graduated in months, weeks, days, or even hours. We need to either change the X-axis label accordingly, or just label it "Time".

![image](https://cloud.githubusercontent.com/assets/329768/18672529/83d2becc-7f16-11e6-9915-72cc84d0a231.png)

**Comment by scloo** [comment]
I'm using 'Time' for now for simplicity because it'll take me time to figure out how dc.js change the X-axis period depending on the date range.

**Comment by gmcressman** [comment]
Done.

**Comment by gmcressman** [comment]
This is a reasonable solution. Done.
