### ISSUE TITLE
Pin "Powered by Coconut Surveillance" to bottom of nav menu.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#248]
![image](https://cloud.githubusercontent.com/assets/329768/18755967/0ebaf166-80bc-11e6-9a63-b30012c1a94f.png)

**Comment by scloo** [comment]
I have been aware of this issue for a while. Just have found the css solution to fix that yet.

**Comment by scloo** [comment]
Trying a new approach by making it vertical on the left of the nav menu.

**Comment by scloo** [comment]
Final position ended up on the bottom right hand corner of screen.

**Comment by gmcressman** [comment]
I like it! Closed.
