### ISSUE TITLE
Graphs: Multiple minor presentation issues

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#249]
![image](https://cloud.githubusercontent.com/assets/329768/18785554/d20f4680-8166-11e6-84ff-e6b7dd40019d.png)

![image](https://cloud.githubusercontent.com/assets/329768/18785716/d68ad804-8167-11e6-99af-79987b028624.png)

**Comment by scloo** [comment]
The X-axis is determine automatically by the DC.js, depending on the date range. And as such I don't know if there is a way to determine that state, without spending hours trying to figure from the complicated library. So I will remove the X-axis label "Time".

**Comment by gmcressman** [comment]
I suspected this may be the case. That means we only have two reasonable options: 1) use “Time”, or 2) don’t use any label.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by gmcressman** [comment]
This will due. Thanks! Closed.
