### ISSUE TITLE
Reports: Case follow-up status - change Shehia risk color

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#252]
Change the color used to identify high-risk shehias to the highlight (red) color. We missed this in our previous working session on this. **One** highlight color for all exceptional data values and issues.

![image](https://cloud.githubusercontent.com/assets/329768/18811500/79557590-827f-11e6-8753-e231ec4e1f17.png)

**Comment by scloo** [comment]
Done

**Comment by gmcressman** [comment]
Done and closed.
