### ISSUE TITLE
Dashboard: Swap Alert and Alarm indicator colors

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#260]
Alarms should be in the MD highlight color, as they are elsewhere in the app.
![image](https://cloud.githubusercontent.com/assets/329768/19077359/532e236a-8a1a-11e6-8981-485ee12c4b97.png)

**Comment by scloo** [comment]
Done

**Comment by gmcressman** [comment]
Done. Closed.
