### ISSUE TITLE
Fix font size in case drill-downs in reports

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#262]
Clicking on an aggregate value in a report displays case IDs, but the font is much to large. Also, "UN" appears to be displayed for all case IDs.
![image](https://cloud.githubusercontent.com/assets/329768/19121570/0518d91e-8af5-11e6-913b-05764ef668fd.png)

**Comment by scloo** [comment]
Unable to reproduce the issue

**Comment by scloo** [comment]
Fixed
