### ISSUE TITLE
Report: Rainfall Submission - how are data entered?

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#269]
How are data entered for rainfall submission?

http://www.syndromic.org/annual-conference/2016-isds-conference/2016-hotel-travel

**Comment by gmcressman** [comment]
Is the mechanism currently in place? Has it been tested?

**Comment by mikeymckay** [comment]
It's in place for the Zanzibar instance. We don't have an SMS gateway that
pushes data into our demo version.
