### ISSUE TITLE
Report: Rainfall Submission - Missing column heading

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#270]
There appears to be a missing column heading on this report, and no data in this column. Is this a bug?

![image](https://cloud.githubusercontent.com/assets/329768/19745632/6dafc2ec-9ba0-11e6-8b66-a1f6501d122e.png)

**Comment by scloo** [comment]
There is not a missing column. The arrow actually refers to the Year column. I'll see if I can move the arrow closer to the column headings.

**Comment by scloo** [comment]
Moved asc/desc icon closer to the column label.
