### ISSUE TITLE
Date picker: previous and next selectors not visible

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#271]
The previous and next selectors are not visible, but they are there, and they do work. Can you reproduce this?

![image](https://cloud.githubusercontent.com/assets/329768/19870263/3be64fc6-9f86-11e6-8250-cc8ff7df015b.png)

**Comment by scloo** [comment]
The date range selector library we are using is called the bootstrap daterangepicker. Which means it is using the bootstrap fonts. So those missing fonts are part of bootstrap which we a not using. I'll have to find a substitution for the missing fonts.

**Comment by gmcressman** [comment]
@scloo - this is strange. Those left and right arrows do appear in older screenshots of the app. They were visible before. Something changed.

**Comment by scloo** [comment]
The old screen shot using the same Date range picker? Unless previously we had the bootstrap installed too, that that might explain it.

**Comment by scloo** [comment]
Fixed by adding the Font Awesome fonts.
