### ISSUE TITLE
Graphs: Move legends to top

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#286]
Is there there an option to move graph legends to the top? That might eliminate the possibility of the data overlapping the legend.
![image](https://cloud.githubusercontent.com/assets/329768/20946104/802bd7f6-bbd7-11e6-9c74-c47417871bce.png)

**Comment by scloo** [comment]
I did not managed to find a quick solution to positioning the legends in a suitable ways either. But I'll revisit this issue.

**Comment by scloo** [comment]
Moved legend below the chart to avoid getting tangled with chart.
