### ISSUE TITLE
Graphs: Adjust spacing between Y-axis label and axis

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#287]
Is there any setting that might prevent the Y-axis label from overlapping the Y-axis tic-mark labels when the tic-mark labels are long?

![image](https://cloud.githubusercontent.com/assets/329768/20946232/ea8029b8-bbd7-11e6-95ea-8dca3366e5c2.png)

**Comment by gmcressman** [comment]
Putting back in In Progress, at bottom of list.

**Comment by scloo** [comment]
No sure why this ticket is back in Progress. The title looks fine to me after the fix. Does this still look overlapping on your screen?

**Comment by gmcressman** [comment]
Move back to In Progress was an error. Moving back to Done.
