### ISSUE TITLE
Dashboard: Add percentages to indicators

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#288]
It would be really useful to add percentages to many of the dashboard indicators:
- Percentage of cases notified that were not followed up
- Percentage of positive cases that were imported (travel history)

Also, I'm no long sure of what "HSAT" and "HSAT Tested" are. I believe the first should be the number of household residents that were tested, and the second should be the number that tested positive. Is that correct?

![image](https://cloud.githubusercontent.com/assets/329768/20946446/afda7b46-bbd8-11e6-8eaa-119966223d1f.png)

**Comment by scloo** [comment]
These numbers were taken from the caseCounter view, which also contains numbers for many other attributes that are to be used in other reports. So when you say percentage, what is the total denominator to base this percentage?

HSAT = Number Household Members Tested Positive
HSAT Tested = Number Household Members Tested
