### ISSUE TITLE
Graphs: Graph title not displayed

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#290]
1. Display dashboard
2. Select graph from dashboard
2. Selected graph is displayed, but title still says "Dashboard". Should change to graph title.

![image](https://cloud.githubusercontent.com/assets/329768/22480629/1231a482-e7c0-11e6-8a9b-98f8ba6e0b2f.png)

**Comment by scloo** [comment]
Issue fixed
