### ISSUE TITLE
Reports: Compare weekly reports and Coconut cases... %>100

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#295]
The data are the calculation are not correct:

![image](https://cloud.githubusercontent.com/assets/329768/24058584/f9c016f6-0b21-11e7-9cd2-419df29e97ff.png)

**Comment by scloo** [comment]
Duplicate of issue# 301

**Comment by gmcressman** [comment]
Closing duplicate.
