### ISSUE TITLE
Date selector toggles multiple times when pressed

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#3]
The Date Selector behaves erratically when pressed. Initially when the dashboard is displayed, the first two reports has no such issue. But as we go down the report list, it starts to toggle multiple times with each one, in increasing number of times as we go down the list.

**Comment by scloo** [comment]
And in some situations clicking the calendar icon does not reveal the Date Filter in the Reports. Clicking the Dashboard link and then return to the Report will fix that. It is a bug.

**Comment by scloo** [comment]
Fixed Bug

**Comment by mikeymckay** [comment]
Nice!
