### ISSUE TITLE
Login forces username to lower case. Validation is case sensitive.

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#303]
User login dialogue forces username to lower case. Validation of the username appears to be case sensitive. Test this by creating a user with a mixed case username.

**Comment by scloo** [comment]
I noticed in the user list in the DB, all the usernames are in lowercase except for two. I'm wondering if this was a later intention to have all the usernames in lowercase?

**Comment by scloo** [comment]
In conjunction with Coconut Mobile, the username is now only in lower case during user create and login.
