### ISSUE TITLE
Increase size of "Add" button and change color

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#304]
Here is the Add button in the Mobile app:
![image](https://cloud.githubusercontent.com/assets/329768/26126852/253bef3c-3a55-11e7-8387-3b334071d70d.png)

There is the Add button in the Analytics app:
![image](https://cloud.githubusercontent.com/assets/329768/26126861/3444e6a0-3a55-11e7-99e9-bc0a4cd54403.png)

Let's try changing the Analytics app to use the larger Add button with the highlight color.

**Comment by scloo** [comment]
Fixed

**Comment by gmcressman** [comment]
Fixed. Closing.
