### ISSUE TITLE
Maps: Cannot read property 'rows'

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#308]
What does this mean? Can it be reproduced?

![image](https://cloud.githubusercontent.com/assets/329768/26726394/d959b63e-4770-11e7-9531-4ca9d77215f2.png)

**Comment by scloo** [comment]
I am not able to reproduce it. What were you doing when you got the error?

**Comment by gmcressman** [comment]
Dumped browser cache.
Logged in.
Selected maps.
Selected grouped points.
Deselected group points.

I can’t reproduce this myself now.

One thing I notice in the console: leaflet is requesting map tiles from google via http rather than https, resulting in warning messages. I doubt this is significant, and I’m not sure there’s an easy fix.

**Comment by scloo** [comment]
Fixed the http connection to google.

**Comment by gmcressman** [comment]
Great. Glad that was a simple fix.

**Comment by gmcressman** [comment]
Cannot reproduce. Closing.
