### ISSUE TITLE
Add issue button control does not function

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#309]
Clicking on the Add Issue (+) button control does nothing due to an uncaught TypeError.
![image](https://user-images.githubusercontent.com/329768/26925783-175022dc-4c19-11e7-9f9c-e5d06c7bb807.png)

**Comment by scloo** [comment]
Was not able to reproduce the problem.

**Comment by gmcressman** [comment]
I can't reproduce this now either. It's disturbing that this issue disappeared. Closing.
