### ISSUE TITLE
Clicking on Edit Issue control displays Dashboard

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#310]
Clicking on the Edit Issue or Delete Issue control displays the Dashboard due to an uncaught TypeError.
![image](https://user-images.githubusercontent.com/329768/26925956-acc74872-4c19-11e7-9a43-52bf5226637b.png)

**Comment by scloo** [comment]
Not able to reproduce the problem.

**Comment by gmcressman** [comment]
I can't either. Closing.
