### ISSUE TITLE
UpdateCaseSummaryDocs script issue

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#315]
This cronjob script is running continuously on the Zanzibar server. It's eating up CPU resources, as well as filling up disk space with the ever increasing couchdb log file.

The issue is due to the fact that Couchdb 2.0 handles changes differently than couchdb 1.6.1 where the 'lastChangeSequenceProcessed'  is stored as an integer. In Couchdb 2.0 it is now stored as a long string. Hence the script fails to compare correctly the values. Hence the script enters into a continuous processing.

**Comment by scloo** [comment]
The UpdateCaseSummaryDocs cron job script is eating up lots of CPU resource. Generally stay 80-100%. If I stop the script, the CPU usage is only in the single digit range.

**Comment by scloo** [comment]
Fixed the bug. The script was updating the 'lastChangeSequenceProcessed' even when there is no change detected.

**Comment by gmcressman** [comment]
This appears to be resolved. Closing.
