### ISSUE TITLE
Admin | DHIS2: Mask password

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#317]
Mask DHIS2 password.
![screen shot 2017-12-20 at 9 53 53 am](https://user-images.githubusercontent.com/329768/34213131-5c9422d4-e56c-11e7-8e9b-4f73f6fdfa4c.png)

**Comment by scloo** [comment]
Done

**Comment by gmcressman** [comment]
Fixed. Closing.
