### ISSUE TITLE
Analysis Report showing incorrect figures for Household visits complete

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#320]
The figures on household visit complete is too low at 90 whereas in the Case Followup report, there are over 2000+ cases completed.

Issue brought up by Humphrey

**Comment by scloo** [comment]
Previous fix of testing for boolean true works for the later case docs. However earlier docs also have the value "true" instead of boolean true.

Added an extra check for the string value of "true" solved the problem.

**Comment by scloo** [comment]
There were other places affected, as highlighted by Humphrey. Found and fixed the codes causing issue.

**Comment by gmcressman** [comment]
Checks correctly against the data.
