### ISSUE TITLE
"How fast are follow-ups occurring" report hung

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#321]
Console shows the following error:

Uncaught (in promise)  Reports.coffee 428

TypeError: Cannot read property 'caseIds' of undefined
    at http://localhost:8081/bundle.js:7473:26
    at Function._.each._.forEach (http://localhost:8081/bundle.js:152547:9)
    at _.(anonymous function) [as each] (http://localhost:8081/bundle.js:153890:34)
    at http://localhost:8081/bundle.js:7469:23
    at <anonymous>

**Comment by scloo** [comment]
This issue is caused by those cases that do not have user attribute value. 
Fixed by added a check for user before executing the codes that follows.

**Comment by gmcressman** [comment]
Fixed.
