### ISSUE TITLE
Compare weekly facility reports with case follow-ups report is not loading

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#323]
Humphrey reported this issue for date range 2017-07-01 to  2017-09-30 for Cases aggregated by Quarter and Facility for All.
![Screen Shot 2018-01-09 at 11.27.14 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ee0c2956415e4abc30254d58eeb9cb74fce36f34985619e8d66c5821c33816aaebd417b853e9728b4f87b5ea8f45c5fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae44854a1113064e674336e0a.png)

**Comment by scloo** [comment]
When I ran the report I did not encounter the problem that Humphrey did. However there were null values in the Zone and District columns as shown in screenshot
![Screen Shot 2018-01-09 at 10.14.27 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2a55415d49bc30254d58eeb9cb74fce36f34985619e8d66c5821c33816aaebd417b853e9728b4f87b5ea8f45c5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae44854a41a3060e07f376e0a.png)


Also there was a whole bunch of console errors about "Can't find facility xxxxxx" as shown in screenshot below:
![Screen Shot 2018-01-09 at 10.16.51 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571a5f9b500b7b0e00eca657/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2a57415a4fbc30254d58eeb9cb74fce36f34985619e8d66c5821c33816aaebd417b853e9728b4f87b5ea8f45c5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae44854a5133f61e777336e0a.png)

**Comment by scloo** [comment]
@mikeymckay What is the difference between the Table Mode and the CSV mode in terms of data being display? I realized that the issue Humphrey brought up was that report is not loading up in CSV mode. 
In the codes, both modes render the same thing. Just that when in cCSV mode, it hides the table data. So I am not sure of the original purpose of having the Table mode and CSV mode.

**Comment by scloo** [comment]
Duplicate of #328

**Comment by gmcressman** [comment]
Fixed. CSV mode question still open for @mikeymckay
