### ISSUE TITLE
Graph: Number of Positive Cases by Age Group does not show index cases

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#327]
There are index cases (positive) with age values during the time period of the graph shown below. Why doesn't the graph show this?

![screen shot 2018-01-30 at 4 08 43 pm](https://user-images.githubusercontent.com/329768/35591589-85a76262-05d8-11e8-889b-5edfd9c35fa9.png)

**Comment by scloo** [comment]
Fixed. 
Changed the condition from
under5 =doc["Number Positive Cases At Index Household And Neighbor Households Under5"]
to
under5 = if doc["Number Positive Cases At Index Household And Neighbor Households Under 5"]? then doc["Number Positive Cases At Index Household And Neighbor Households Under 5"] else doc["Number Positive Cases At Index Household And Neighbor Households Under5"]

**Comment by gmcressman** [comment]
This looks correct now. I compared it with some of the data. I will do a more thorough check before closing this.

**Comment by gmcressman** [comment]
Checks against the data. Looks ok now.
