### ISSUE TITLE
Remove left and right borders on tables

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#39]
Removing the left and right borders on tables would help open up the displays. This would also be consistent with MD data tables. This is a minor point and preference, but can this change be made in a single location?

![image](https://cloud.githubusercontent.com/assets/329768/15117119/17f843e4-15d4-11e6-9105-c406fabe2d16.png)

**Comment by scloo** [comment]
This is actually the MDL data table look.
https://getmdl.io/components/index.html#tables-section

https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction

**Comment by gmcressman** [comment]
@scloo, is this table border coming directly from MD Lite?

**Comment by scloo** [comment]
@gmcressman Yes it is.

**Comment by gmcressman** [comment]
Then, much as I dislike it, it will stay that way for now.
