### ISSUE TITLE
Admin: Users - mask passwords

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#40]
Mask user passwords on all displays.

Do we need a reveal/hide control on the modal detail dialog?

![image](https://cloud.githubusercontent.com/assets/329768/15117161/5267dba2-15d4-11e6-8838-37f6bec4e73c.png)

![image](https://cloud.githubusercontent.com/assets/329768/15117196/75fe6c48-15d4-11e6-9769-5e46423b22fe.png)

**Comment by gmcressman** [comment]
Still not done on http://cococloud.co/zanzibar/_design/analytics/index.html#admin/users. Is this a change that has not been pushed?

**Comment by scloo** [comment]
I have only masked the password form in the Users listing but not in the edit mode. This is temporarily not masked because it does need a rewrite of the codes to hash the password, as well as to save the data.

**Comment by gmcressman** [comment]
Shall we leave this in In Process?

**Comment by gmcressman** [comment]
@scloo , I no longer see the password field in the add/edit modal dialogue for users. Shouldn't it be there, but masked, so an admin can create and change passwords?

**Comment by scloo** [comment]
I'm working on the module to allow the user themselves to reset their password. So there should be no need for the admin to change password. Unless you see a reason for the admin to be able to do that.

**Comment by gmcressman** [comment]
@mikeymckay should weigh in on this. I suspect there are situations where the user cannot access email to reset their password. In that case they may contact an admin and ask them to reset the password.

On a separate note, shouldn’t the Role field in the profile be a list?

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by mikeymckay** [comment]
Most important is the need an admin to reset the password and know what that password is. It would be reasonable for the user to reset their own password as well, but as Gordon said, access to email is questionable. Probably access to SMS is better.

**Comment by scloo** [comment]
Admin can now reset password in the Admin/User view. The password input will be in plain text so that the admin can see what he/she is typing. Upon saving, the password will be saved as a hash. Currently the new doc attribute is called hash.
