### ISSUE TITLE
Admin: Users - Improve handling of "Inactive" field

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#41]
- [ ] Change data in "Inactive" column do that it is boolean.
- [ ] Display values in this column as "Yes" or "No", or just display the sliders in the column. If the latter, use a modal dialog to get confirmation from the user before changing the value. 

I suggest changing the name of this field to "Active". It is simpler and more direct.

![image](https://cloud.githubusercontent.com/assets/329768/15117303/e988028c-15d4-11e6-93c8-5ddf3eafd218.png)

![image](https://cloud.githubusercontent.com/assets/329768/15117477/bce9b27e-15d5-11e6-93c4-fa0d8f06be73.png)

**Comment by scloo** [comment]
Changing the label is easy. However this does involve updating the data structure in DB and updating the data. And then updating the previous codes that refers to the field inactive.

**Comment by gmcressman** [comment]
It's not necessary to change the underlying data type. However, regardless of how it's done, the display should show only two values or states (e.g. "Yes" | "No", or the slider).
