### ISSUE TITLE
Store user passwords in hashed form

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#43]
Discuss this with Mike. crypto.js one option for the necessary functions. It does include a small MD5 module.

**Comment by scloo** [comment]
Encryption is added for password. However the current password is still plain text in each doc. Eventually have to be converted to encrypted form and then deleted from the doc.

**Comment by scloo** [comment]
Closing ticket and opening another to take care of conversion of current plain text passwords to hash passwords.
