### ISSUE TITLE
Unable to log in using Chrome

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#54]
Chrome Version 50.0.2661.102 (64-bit)
Cleared cache using Clear Cache  1.1.2 Extension

Logged in using admin UN/PW.
![image](https://cloud.githubusercontent.com/assets/329768/15441847/41ba6e98-1eab-11e6-9f9f-499af9d1041e.png)

"null" displayed for username in header strip. No drawer menu items function; they do not display anything in the content area. 
![image](https://cloud.githubusercontent.com/assets/329768/15441757/bf4c152e-1eaa-11e6-8162-22f25660344b.png)

Same behavior seen in Firefox and Safari. 

Login appears to be broken.

**Comment by scloo** [comment]
It was a bug. Was using hardcoded url using localhost for the database. Bug fixed.

**Comment by gmcressman** [comment]
Yeah! Check for any other hard coded URLs.
