### ISSUE TITLE
Add Search capability to Users page

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#58]
See brilliant search example on Facilities page.

**Comment by gmcressman** [comment]
Could use icon for search. See good example on hub.tangerinecentral.org:

![image](https://cloud.githubusercontent.com/assets/329768/15686274/86bdeb1a-273d-11e6-9781-3c71397da0a7.png)

**Comment by scloo** [comment]
The search feature in this case is part of the DataTable library. It may be possible to customize it with a search icon. Need to find out whether this is possible.
