### ISSUE TITLE
PII/PHI not hashed before display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#63]
PII/PHI should be hashed before display and before export of any data in Analytics. Only authorized users of the mobile app should have access to this information. This is the case with the previous version. Also, check the security level of the hashing algorithm. 

![image](https://cloud.githubusercontent.com/assets/329768/15678235/8a3c4a24-271b-11e6-9c5f-5469fa86c206.png)

**Comment by scloo** [comment]
The hashing will only apply to non-admin users. Administrator will still be able to view the PII/PHI. To test this login in as user 'test'
