### ISSUE TITLE
Is there any way to reduce delay when going between Case Follow-up Status and detail?

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#64]
When navigating between the Case Follow-up Status report and case-level detail, using links on the report, the query is rerun before the Case Follow-up Status report is displayed again.

Display Case Follow-up Status
Click on any of the icons to display the case detail.
Click on the browser back arrow or reselect the Case Follow-up Status report
The query is run again before the Case Follow-up Status report is displayed

If the user is navigating back and forth between the report and the case detail, this makes it a slow process. Is there any way to speed this up?

**Comment by scloo** [comment]
Unfortunately, going back to previous page is equivalent to reloading the Backbone view. And that involves reloading the data. So in the current workflow, I'm not aware of a way to avoid not reloading. Maybe possible to use caching but I'm not familiar with this technique. Another option would be when clicking the icon for more detail, this will open a modal with the details. In which case, closing the modal will return to previous page without reloading.

**Comment by scloo** [comment]
Implemented using a modal to view cases. 
One more thing to do is to go to the proper table based on the case type clicked.

**Comment by scloo** [comment]
Created a new ticket #110 for the remaining enhancement.
