### ISSUE TITLE
npm script issue

### ISSUE THREAD

**Issue by scloo** [ICTatRTI/coconut-analytics#7]
The sed -i "s/......./ app/start.coffee" command is not working correctly. When doing "npm run dev" it is not substituting correctly and hence still getting data from cococloud.co instead of localhost.

I have updated the script to:
"sed 's/https:\\/\\/cococloud.co\\/zanzibar/http:\\/\\/localhost:5984\\/zanzibar/' app/start.coffee  & npm run watch & npm run livereload & npm run static"

It is substituting correctly now but not writing back to the file. Hence when creating bundle.js, it is still using the same old start.coffee file.

**Comment by mikeymckay** [comment]
@scloo not sure why you had the first empty quote after the sed command. I removed that and it works fine. The original problem was that we needed to doubly escape the backslashes, which it looks like you did.

**Comment by scloo** [comment]
The first empty quote is to skip making a backup file. If I remember it correctly, when there is no backup file name specified, and no empty quote, it will not write back to the source file. And hence when browserify does its job, it takes the original file minus the change.
