### ISSUE TITLE
Remove "USSD" from Case Follow-up Status report

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#71]
![image](https://cloud.githubusercontent.com/assets/329768/15683208/2c2f8dec-272f-11e6-9c45-fdec91582f19.png)
"USSD" is the specific technology used in MEEDS. We need to generalize this app. Case notifications can come from many sources, including USSD, SMS, and other sources. We currently have "USSD Notification" and "Case Notification" columns. We also use these same terms elsewhere in the app. How can we generalize these? Could we use:

Case Notification Sent
Case Notification Received

**Comment by gmcressman** [comment]
Mike approved.

**Comment by scloo** [comment]
Mike,  I realized that this may be more than merely a change of the column title wording. Are there any references in the data that refers to "USSD Notification" . I noticed that the number in parenthesis in the header title is tied to the title wording. In this case "USSD Notification". Changing it to "Notification Received" will cause the number to be zero. So is there any where within the CouchDB doc that refers to "USSD Notification" ?

**Comment by gmcressman** [comment]
@mikeymckay , same issue here with the case detail displays:
![image](https://cloud.githubusercontent.com/assets/329768/16381159/203d0abc-3c49-11e6-8770-edbf1bb5c4e7.png)

**Comment by mikeymckay** [comment]
Yes - these all refer to specific types of results. There is a property on
a result called "question" and we use this directly.  Changing this will
make things messier. I think it makes sense to change it in the column
header, but not on the case detail page.

**Comment by gmcressman** [comment]
I understand. That makes sense to me: change it in the column headers of reports, but not in the detail page.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by gmcressman** [comment]
@scloo , is it possible to change the column headings to "Case Notification Sent" and "Case Notification Received"?

**Comment by scloo** [comment]
Done. Waiting to be pushed to cococloud.co
