### ISSUE TITLE
Link from Case Follow-up Status report to correct location in case detail record

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#72]
When a user selects and icon on the Case Follow-up Status report, the previous version of the reporting app takes the user directly to the appropriate section of the case record. The Analytics app currently takes the user to the top of the case record.

**Comment by gmcressman** [comment]
This is not working with the model dialog. Regardless of which stage-icon I select on the follow-up report, it displays the detail starting at the top.

**Comment by scloo** [comment]
Seems erratic . Most of the time it works but sometimes it does. So far unable to spot the bug yet.

**Comment by scloo** [comment]
Bug fixed.

**Comment by gmcressman** [comment]
@scloo I see no change on cococloud. Has this been deployed?

**Comment by scloo** [comment]
Yes, it has been deployed and it works from my machine. Try Shift + Reload on that report page.
