### ISSUE TITLE
Case Follow-up Status: Some column counts not correct

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#74]
Some of the counts in the column headings are not correct:

![image](https://cloud.githubusercontent.com/assets/329768/15683587/262f552e-2731-11e6-9cd9-a66fa1b8f9b2.png)

**Comment by scloo** [comment]
Apparently this is showing the same thing in the current Coconut version.

**Comment by scloo** [comment]
The count within the parenthesis is a count of the number of buttons/icons within each of the columns. For columns 2,3 and 4 there are no buttons/icons and hence gives zero count. Though it is redundant but is part of a loop code that generates the count. So these columns will always be zero.

**Comment by gmcressman** [comment]
Then let’s remove the counts for those columns. The zero counts will just confuse users, such as me.

-gmc

Gordon M. Cressman
Senior Program Director | Research Computing Division | RTI International
Email: gmc@rti.org<mailto:gmc@rti.org> | Office: +1 919 541-6363 | Mobile: +1 919 271-7003 | Skype: gmcressman

Was this email too brief? Here is why<http://emailcharter.org/>

**Comment by scloo** [comment]
Counts removed from those three columns.
