### ISSUE TITLE
Period Trends: Complete detail report display

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#80]
User selects number on the main report to display a more detailed report. It does not appear that the detailed report display has been completed. It also still shows the toggle control, which does not appear to be used on this display. I'm not sure how useful this detailed report is. The old reporting app will display a link to each case report. If there are many, I wonder just how useful that is.

![image](https://cloud.githubusercontent.com/assets/329768/15684962/a281ac98-2737-11e6-80b4-ce057c423c86.png)

**Comment by scloo** [comment]
Moved to Closed by mistake and reopen to move to Review status

**Comment by gmcressman** [comment]
There seems to be a problem with the detail:
![image](https://cloud.githubusercontent.com/assets/329768/16012266/b641ed14-3156-11e6-9544-33351e89ccd8.png)

**Comment by scloo** [comment]
I think this is a data error. Perhaps incorrect data. The same thing happens on the current coconut version.

**Comment by scloo** [comment]
Problem fixed. Waiting to be pushed to GitHub
