### ISSUE TITLE
Should assignee's name be displayed in Activities:Issues table?

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#86]
![image](https://cloud.githubusercontent.com/assets/329768/15687753/55d33256-2744-11e6-9b66-7b77e290141d.png)

**Comment by scloo** [comment]
Issue fixed

**Comment by scloo** [comment]
Broke after fixing issue #190. Now fixed.

**Comment by gmcressman** [comment]
Still appears to have a problem. Please check.
![image](https://cloud.githubusercontent.com/assets/329768/17140250/cdd392da-5315-11e6-9cdf-a4a1ee9cd4fa.png)
