### ISSUE TITLE
Data Export: Complete data download page

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#92]
- [ ] "Data Export" or "Export Data"? @cjenkins-rti ?
- [x] Use MD cloud download icon on DOWNLOAD button?
- [ ] Get download function working correctly with date selector.
- [x] Add spinner to indicate activity while download is in process.

Do we anticipate adding any other download formats (e.g. CSV)? If so, we'll need to modify this page somewhat.

**Comment by scloo** [comment]
Able to download the spreadsheets but unable to find the codes that produce the spreadsheet. This is being downloaded from the url spreadsheet.zmcp.org. Need to be local in order to be generic.

**Comment by scloo** [comment]
Since this is ruby code, will need to update the codes later. So I'll consider this as done.

**Comment by gmcressman** [comment]
Keep this open until it is complete, or post separate issues.

**Comment by gmcressman** [comment]
Data selector currently has no affect on what data are exported.

Consider a modal dialog to notify use that download is complete? Is this a bad idea for a responsive app? Let's see what @cjenkins-rti thinks.

**Comment by scloo** [comment]
The dates were not submitted for the data download. I fixed that. But not sure if the results are within this date range. I do not know which date field in the db is used to compare.

**Comment by gmcressman** [comment]
URL needs to be corrected. Needs guidance from Mike.

**Comment by gmcressman** [comment]
@mikeymckay: There are multiple exported files - one for each question set. The dates appear to be in line with those in the date selector, but are sometimes a bit out of this range, depending on which file and date columns that I check. I have a feeling that it's exporting the correct data, but it would very useful to know precisely which dates on which records are being used to filter the exported data.  This would be useful for the documentation.
