### ISSUE TITLE
Report: Implement case drill-down for Period trends compared to previous three weeks

### ISSUE THREAD

**Issue by gmcressman** [ICTatRTI/coconut-analytics#97]
![image](https://cloud.githubusercontent.com/assets/329768/15875141/89b80bc4-2cd4-11e6-9e3c-6d2e131c5ac7.png)

**Comment by scloo** [comment]
When I last checked it was already implemented.

**Comment by gmcressman** [comment]
It's working. Now. I don't know why it was not working on June 7. Closed.
